# run_numbat.py


import os
import shutil
import stat
import subprocess
import sys
import time
from logging import error


def run_numbat(
    sample_id,
    bam_fn,
    barcode_fn,
    matrix_dir,
    out_dir,
    cell_anno_fn,
    ref_cell_types,
    ncores,
    pp_script_fn,     # the pileup_and_phasing.R
    eagle_fn,
    gmap_fn,
    snp_vcf_fn,
    panel_dir,
    platform,
    genome,
    gamma = 20,
    script_dir = None
):
    os.makedirs(out_dir, exist_ok = True)

    pp_dir = os.path.join(out_dir, "allele")
    os.makedirs(pp_dir, exist_ok = True)

    if script_dir is None:
        script_dir = os.path.join(out_dir, "scripts")
    os.makedirs(script_dir, exist_ok = True)

    pp_script_fn_new = copy_file(pp_script_fn, script_dir)

    run_numbat_pp(
        sample_id = sample_id,
        bam_fn = bam_fn,
        barcode_fn = barcode_fn,
        out_dir = pp_dir,
        ncores = ncores,
        pp_script_fn = pp_script_fn_new,
        eagle_fn = eagle_fn,
        gmap_fn = gmap_fn,
        snp_vcf_fn = snp_vcf_fn,
        panel_dir = panel_dir,
        platform = platform,
        script_fn = os.path.join(script_dir, "numbat.pp.sh")
    )

    ret = run_numbat_call(
        sample_id = sample_id,
        allele_fn = os.path.join(pp_dir, "%s_allele_counts.tsv.gz" % sample_id),
        matrix_dir = matrix_dir,
        out_dir = os.path.join(out_dir, "cna"),
        cell_anno_fn = cell_anno_fn,
        ref_cell_types = ref_cell_types,
        ncores = ncores,
        out_prefix = "%s.numbat" % sample_id,
        genome = genome,
        gamma = gamma,
        script_fn = os.path.join(script_dir, "numbat.call.R")
    )
    return(ret)



def run_numbat_call(
    sample_id,
    allele_fn,
    matrix_dir,
    out_dir,
    cell_anno_fn,
    ref_cell_types,
    ncores,
    out_prefix,
    genome,
    gamma = 20,
    script_fn = None
):
    s  = '''# run Numbat CNA calling.\n'''
    s += '''\n'''
    s += '''library(numbat)\n'''
    s += '''library(Seurat)\n'''
    s += '''\n'''
    s += '''run_numbat_call <- function(\n'''
    s += '''    allele_fn, count_mtx_dir, out_dir,\n'''
    s += '''    cell_anno_fn, ref_cell_types,\n'''
    s += '''    ncores, out_prefix,\n'''
    s += '''    genome, gamma)\n'''
    s += '''{\n'''
    s += '''    # check args\n'''
    s += '''    if (! dir.exists(out_dir)) {\n'''
    s += '''        dir.create(out_dir, recursive = T)\n'''
    s += '''    }\n'''
    s += '''    setwd(out_dir)\n'''
    s += '''    if (! genome %in% c("hg19", "hg38"))\n'''
    s += '''        stop(sprintf("invalid genome version '%s'.", genome))\n'''
    s += '''\n'''
    s += '''\n'''
    s += '''    # filter ref cells from allele dataframe\n'''
    s += '''    baf <- read.delim(allele_fn, header = T, stringsAsFactors = F)\n'''
    s += '''    cell_anno <- read.delim(cell_anno_fn, header = F, stringsAsFactors = F)\n'''
    s += '''    colnames(cell_anno) <- c("cell", "group")\n'''
    s += '''    ref_cells <- cell_anno[cell_anno$group %in% ref_cell_types, ]\n'''
    s += '''    baf_noref <- baf[! (baf$cell %in% ref_cells$cell), ]\n'''
    s += '''    saveRDS(baf_noref, sprintf('''
    s += '''        "%s/%s.ref_filtered.allele.df.rds", out_dir, out_prefix))\n'''
    s += '''\n'''
    s += '''\n'''
    s += '''    # filter ref cells from count matrix\n'''
    s += '''    rdr <- Seurat::Read10X(data.dir = count_mtx_dir)   # gene x cell\n'''
    s += '''    rdr_noref <- rdr[, ! (colnames(rdr) %in% ref_cells$cell)]\n'''
    s += '''    saveRDS(rdr_noref, sprintf('''
    s += '''        "%s/%s.ref_filtered.count.mtx.rds", out_dir, out_prefix))\n'''
    s += '''\n'''
    s += '''\n'''
    s += '''    # calculate average expression of ref cells\n'''
    s += '''    ref_mean_expr <- numbat::aggregate_counts(rdr, ref_cells)\n'''
    s += '''    saveRDS(ref_mean_expr, sprintf('''
    s += '''        "%s/%s.ref.gene_by_celltype.mtx.rds", out_dir, out_prefix))\n'''
    s += '''\n'''
    s += '''    obj <- run_numbat(\n'''
    s += '''        rdr_noref,         # gene x cell integer UMI count matrix \n'''
    s += '''        ref_mean_expr,     # reference expression profile, a gene x cell type normalized expression level matrix\n'''
    s += '''        baf_noref,         # allele dataframe generated by pileup_and_phase script\n'''
    s += '''        genome = genome,\n'''
    s += '''        t = 1e-5,\n'''
    s += '''        gamma = gamma,\n'''
    s += '''        ncores = ncores,\n'''
    s += '''        plot = TRUE,\n'''
    s += '''        out_dir = out_dir\n'''
    s += '''    )\n'''
    s += '''    saveRDS(obj, sprintf("%s/%s.out.object.rds", out_dir, out_prefix))\n'''
    s += '''}\n'''
    s += '''\n'''
    s += '''\n'''
    s += '''run_numbat_call(\n'''
    s += '''    allele_fn = "%s",\n''' % allele_fn
    s += '''    count_mtx_dir = "%s",\n''' % matrix_dir
    s += '''    out_dir = "%s",\n''' % out_dir
    s += '''    cell_anno_fn = "%s",\n''' % cell_anno_fn

    if ref_cell_types is None:
        s += '''    ref_cell_types = NULL,\n'''
    elif isinstance(ref_cell_types, str):
        s += '''    ref_cell_types = c("%s"),\n''' % ref_cell_types
    else:
        s += '''    ref_cell_types = %s,\n''' % \
            iter2c(ref_cell_types, dtype = 'str')

    s += '''    ncores = %d,\n''' % ncores
    s += '''    out_prefix = "%s",\n''' % out_prefix
    s += '''    genome = "%s",\n''' % genome
    s += '''    gamma = %f\n''' % gamma
    s += ''')\n'''
    s += '''\n'''
    s += '''print("[Numbat] All Done!")\n'''
    s += '''\n'''

    os.makedirs(out_dir, exist_ok = True)

    if script_fn is None:
        script_fn = os.path.join(out_dir, "numbat.call.R")

    with open(script_fn, "w") as fp:
        fp.write(s)
    set_file_exe(script_fn)

    cmd = "/usr/bin/time -v Rscript %s" % script_fn
    ret, outs, errs = run_cmd(cmd)
    return(ret)



def run_numbat_pp(
    sample_id,
    bam_fn,
    barcode_fn,
    out_dir,
    ncores,
    pp_script_fn,
    eagle_fn,
    gmap_fn,
    snp_vcf_fn,
    panel_dir,
    platform,
    script_fn = None
):
    s  = '''#!/bin/bash\n'''
    s += '''# run Numbat preprocessing.\n'''
    s += '''\n'''
    s += '''Rscript  %s   \\\n''' % pp_script_fn
    s += '''    --label  %s    \\\n''' % sample_id
    s += '''    --samples  %s    \\\n''' % sample_id
    s += '''    --bams  %s    \\\n''' % bam_fn
    s += '''    --barcodes  %s    \\\n''' % barcode_fn
    s += '''    --outdir  %s    \\\n''' % out_dir
    s += '''    --ncores  %s    \\\n''' % ncores
    s += '''    --eagle  %s    \\\n''' % eagle_fn
    s += '''    --gmap  %s    \\\n''' % gmap_fn
    s += '''    --snpvcf  %s    \\\n''' % snp_vcf_fn
    s += '''    --paneldir  %s    \\\n''' % panel_dir

    if platform == "10x":
        s += "\n"
    elif platform == "smartseq":
        s += "--smartseq    \n"
    elif platform == "bulk":
        s += "--bulk    \n"
    else:
        raise ValueError("unknown platform '%s'!" % platform)

    s += '''\n'''

    os.makedirs(out_dir, exist_ok = True)

    if script_fn is None:
        script_fn = os.path.join(out_dir, "numbat.pp.sh")

    with open(script_fn, "w") as fp:
        fp.write(s)
    set_file_exe(script_fn)

    cmd = "/usr/bin/time -v %s" % script_fn
    ret, outs, errs = run_cmd(cmd)
    return(ret)



def copy_file(src, dst):
    return shutil.copy2(src, dst)


def iter2c(items, dtype = 'int'):
    s = "c("
    for i, x in enumerate(items):
        if i > 0:
            s += ", "
        if dtype == 'int':
            s += "%d" % x
        elif dtype == 'str':
            s += '''"%s"''' % x
        else:
            raise ValueError()
    s += ")"
    return(s)


def run_cmd(args, check_retcode = False):
    proc = subprocess.Popen(
        args = args,
        shell = True,
        executable = "/bin/bash",
        stdout = subprocess.PIPE,
        stderr = subprocess.PIPE
    )
    outs, errs = proc.communicate()
    ret = proc.returncode
    if ret != 0:
        error(str(errs.decode()))
        if check_retcode:
            raise RuntimeError
    return(ret, outs, errs)


def set_file_exe(fn):
    st = os.stat(fn)
    os.chmod(fn, st.st_mode | stat.S_IXUSR)



if __name__ == "__main__":
    run_numbat(
        sample_id = 'HCC3N_simu',
        bam_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/cna_prediction/1n1t_s1600/downsample_coverage/ds_50perc/gen_data/subset_bam/possorted.bam',
        barcode_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/cna_prediction/1n1t_s1600/downsample_coverage/ds_50perc/gen_data/rdr_starsolo/barcodes.tsv',
        matrix_dir = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/cna_prediction/1n1t_s1600/downsample_coverage/ds_50perc/gen_data/rdr_starsolo',
        out_dir = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/cna_prediction/1n1t_s1600/downsample_coverage/ds_50perc/cna_calling/numbat',
        cell_anno_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/cna_prediction/1n1t_s1600/base/data/matrix/spot_anno.tsv',
        ref_cell_types = 'normal',
        ncores = 10,
        pp_script_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/base/data/refapp/numbat/pileup_and_phase.R',
        eagle_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/base/data/refapp/eagle/eagle',
        gmap_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/base/data/refapp/eagle/genetic_map_hg38_withX.txt.gz',
        snp_vcf_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/base/data/refapp/phasing/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf.gz',
        panel_dir = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/base/data/refapp/phasing/1000G_hg38',
        platform = '10x',
        genome = 'hg38',
        gamma = 20,
        script_dir = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/cna_prediction/1n1t_s1600/downsample_coverage/ds_50perc/cna_calling/numbat/scripts'
    )
